# Generated by Django 6.0 on 2026-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer Out', 'Transfer Out'), ('Transfer In', 'Transfer In'), ('Service Fee', 'Service Fee')], max_length=20),
        ),
    ]
